[workspace]

members = [
    "monoio-server",
    "tokio-server",
    "tokio-uring-server",
    "glommio-server",

    "client",

    "config"
]

[profile.release]
lto = true
debug = false
overflow-checks = false
